### ISSUE TITLE
[Question] Requirement

### ISSUE THREAD

**Issue by kenakamu** [aromajoin/hackaroma#5]
Hi team,

I have two questions.

- Is it mandatory to use AWS IoT?
- Is it okay to develop an application only work with a particular individual or it has to work with judge's shooter as well?

**Comment by trungchubao** [comment]
Hi,

Thanks for your questions. Please find the answers below:

- We want to make the world's first livestreaming of scent data. So we highly recommend applicants to use AWS IoT so that the app can control Aroma Shooters over the internet. Also, using AWS IoT in general is not more difficult than using our SDKs. Teams can go without building on AWS IoT, but the evaluation should be affected hugely.

- The second problem should be addressed by the above answer. Not mandatory, but the difference between making it for remote Aroma Shooters and not making it is huge.

**Comment by kenakamu** [comment]
okay thanks. I was planning to do something more individual stuff before reading the requirement, but now I understand it. Thanks for your answer.
